/*
 * smp.c — Application Processor (AP) bootstrap engine for PhotonOS SMP.
 *
 * Responsibilities:
 *   1. Copy the 16-bit trampoline binary blob to physical 0x7000.
 *   2. Allocate isolated 4 KiB stacks per AP via pmm_alloc().
 *   3. Write per-AP boot parameters (CR3, RSP, AP_ID, ENTRY) to fixed
 *      trampoline offsets before firing the INIT-SIPI sequence.
 *   4. Implement ap_kmain() — the C landing pad for every secondary core.
 *
 * Ring 0 contract: klog() accepts ONLY static literal strings.
 * All volatile shared state uses __sync_* GCC atomics or volatile pointers.
 */

#include "smp.h"
#include "apic.h"
#include "memory.h"
#include "serial.h"

/* ── Linker symbols generated by:  ld -r -b binary trampoline.bin -o trampoline_blob.o ── */
extern const uint8_t _binary_trampoline_bin_start[];
extern const uint8_t _binary_trampoline_bin_end[];

/* ── Constants ── */
#define TRAMPOLINE_PHYS_BASE   0x7000ULL
#define PMM_PAGE_SIZE_LOCAL    4096ULL
#define MAX_CORES              4          /* BSP + up to 3 APs for now         */

/* ── Fixed parameter offsets inside the trampoline page (from 0x7000) ── */
#define TRAMP_OFFSET_CR3       0x10       /* uint64_t: kernel PML4 physical addr */
#define TRAMP_OFFSET_RSP       0x18       /* uint64_t: AP stack top pointer      */
#define TRAMP_OFFSET_ID        0x20       /* uint64_t: logical AP core ID        */
#define TRAMP_OFFSET_READY     0x28       /* uint64_t: AP sets to 1 when ready   */
#define TRAMP_OFFSET_ENTRY     0x30       /* uint64_t: ap_kmain() virtual address */

/* ── APIC ICR register offsets (relative to LAPIC MMIO base) ── */
#define LAPIC_ICR_HIGH  APIC_REG_ICR_HIGH  /* 0x310 */
#define LAPIC_ICR_LOW   APIC_REG_ICR_LOW   /* 0x300 */

/* ── IPI command words ── */
#define IPI_INIT        0x00004500UL       /* INIT IPI — assert               */
#define IPI_SIPI_VEC07  0x00004607UL       /* STARTUP IPI — vector 0x07 → 0x7000 */

/* ── BSP GDTR saved at early kernel init for AP reload ── */
struct gdtr_record {
    uint16_t limit;
    uint64_t base;
} __attribute__((packed));

static struct gdtr_record bsp_gdtr;

/* ── Global SMP spinlock (used in ap_kmain for serialized log output) ── */
static spinlock_t smp_lock;

/* ── Number of APs that have completed boot ── */
static volatile int ap_booted_count = 0;

/* ════════════════════════════════════════════════════════════════════════════
 * Spinlock primitives — thin wrappers over GCC built-in atomics.
 * ════════════════════════════════════════════════════════════════════════════ */

void spin_init(spinlock_t *lock)
{
    lock->locked = 0;
    __sync_synchronize();
}

void spin_lock(spinlock_t *lock)
{
    while (__sync_lock_test_and_set(&lock->locked, 1)) {
        /* PAUSE: reduce memory-bus pressure while spinning */
        __asm__ volatile ("pause" ::: "memory");
    }
}

void spin_unlock(spinlock_t *lock)
{
    __sync_lock_release(&lock->locked);
}

/* ════════════════════════════════════════════════════════════════════════════
 * Internal helpers
 * ════════════════════════════════════════════════════════════════════════════ */

/* Plain byte-copy — no libc available in Ring 0. */
static void mem_copy(void *dst, const void *src, uint64_t n)
{
    uint8_t       *d = (uint8_t *)dst;
    const uint8_t *s = (const uint8_t *)src;
    for (uint64_t i = 0; i < n; i++) {
        d[i] = s[i];
    }
}

/* Write a 64-bit value to an absolute physical/virtual address. */
static inline void write64_at(uintptr_t addr, uint64_t value)
{
    volatile uint64_t *ptr = (volatile uint64_t *)addr;
    *ptr = value;
}

/* Read a 64-bit value from an absolute physical/virtual address. */
static inline uint64_t read64_at(uintptr_t addr)
{
    volatile const uint64_t *ptr = (volatile const uint64_t *)addr;
    return *ptr;
}

/* Read current CR3 (kernel PML4 physical base). */
static inline uint64_t read_cr3(void)
{
    uint64_t cr3;
    __asm__ volatile ("mov %%cr3, %0" : "=r"(cr3));
    return cr3;
}

/* Read TSC counter for delay calibration. */
static inline uint64_t rdtsc(void)
{
    uint32_t lo, hi;
    __asm__ volatile ("rdtsc" : "=a"(lo), "=d"(hi));
    return ((uint64_t)hi << 32) | lo;
}

/*
 * delay_rdtsc_approx_10ms — busy-wait approximately 10 milliseconds.
 *
 * Calibrated for a conservative minimum TSC rate of 100 MHz (QEMU default
 * is typically 1 GHz, real hardware is ≥ 1 GHz).  At 100 MHz 10 ms = 1M
 * cycles.  Using 2M cycles gives comfortable margin on any modern CPU.
 */
static void delay_rdtsc_approx_10ms(void)
{
    const uint64_t TICKS_10MS = 2000000ULL;
    uint64_t start = rdtsc();
    while ((rdtsc() - start) < TICKS_10MS) {
        __asm__ volatile ("pause" ::: "memory");
    }
}

/* ════════════════════════════════════════════════════════════════════════════
 * Vector A — Copy trampoline + save BSP GDTR.
 * ════════════════════════════════════════════════════════════════════════════ */

void smp_init(void)
{
    /* ── 1. Save BSP GDTR so APs can reload the real kernel GDT later. ── */
    __asm__ volatile ("sgdt %0" : "=m"(bsp_gdtr));

    /* ── 2. Initialise the global SMP spinlock. ── */
    spin_init(&smp_lock);

    /* ── 3. Copy trampoline raw binary to physical page 0x7000. ──
     *
     * The identity-mapped page tables built at boot guarantee that virtual
     * address 0x7000 == physical 0x7000 and is both present and writable.
     */
    const uint8_t *src   = _binary_trampoline_bin_start;
    const uint8_t *end   = _binary_trampoline_bin_end;
    uint64_t       size  = (uint64_t)(end - src);

    void *tramp_dest = (void *)TRAMPOLINE_PHYS_BASE;
    mem_copy(tramp_dest, src, size);

    /* Memory barrier: ensure all writes to 0x7000 are visible before any IPI. */
    __asm__ volatile ("" ::: "memory");

    klog("SMP: trampolim de 16-bit copiado para 0x7000.\n");
}

/* ════════════════════════════════════════════════════════════════════════════
 * Vector B + C — Allocate stack, write parameters, fire INIT-SIPI.
 * ════════════════════════════════════════════════════════════════════════════ */

void smp_boot_ap(uint8_t ap_id)
{
    /* ── Vector B: Allocate a dedicated 4 KiB stack page for this AP. ── */
    void *stack_phys = pmm_alloc();
    if (stack_phys == 0) {
        klog("SMP: falha ao alocar pilha para AP.\n");
        return;
    }

    /*
     * Stack top = base + PAGE_SIZE.  The stack grows downward in x86_64,
     * so RSP must start at the highest valid address of the allocated page.
     */
    uint64_t stack_top = (uint64_t)stack_phys + PMM_PAGE_SIZE_LOCAL;

    /* ── Write parameters to fixed trampoline offsets ── */
    /* CR3: physical address of the kernel PML4 */
    write64_at(TRAMPOLINE_PHYS_BASE + TRAMP_OFFSET_CR3,   read_cr3());
    /* RSP: top of the newly allocated AP stack */
    write64_at(TRAMPOLINE_PHYS_BASE + TRAMP_OFFSET_RSP,   stack_top);
    /* AP logical ID passed as argument to ap_kmain */
    write64_at(TRAMPOLINE_PHYS_BASE + TRAMP_OFFSET_ID,    (uint64_t)ap_id);
    /* READY flag must be zero before we fire; AP will set it to 1 */
    write64_at(TRAMPOLINE_PHYS_BASE + TRAMP_OFFSET_READY, 0ULL);
    /* Entry point: virtual address of the C function ap_kmain */
    write64_at(TRAMPOLINE_PHYS_BASE + TRAMP_OFFSET_ENTRY, (uint64_t)(uintptr_t)ap_kmain);

    /* Full memory barrier — Intel SDM §10.12.1 requires all prior stores
     * to be globally visible before writing ICR. */
    __asm__ volatile ("" ::: "memory");

    /* ── Vector C: Transmit INIT-SIPI-SIPI sequence via BSP LAPIC ICR. ── */

    /*
     * Step 1: Select destination AP.
     * ICR_HIGH bits 31:24 = Destination APIC ID.
     * Logical AP ID == APIC ID in single-socket flat configurations.
     */
    apic_write(LAPIC_ICR_HIGH, (uint32_t)ap_id << 24);

    /*
     * Step 2: Assert INIT IPI.
     * Delivery Mode = INIT (101b), Trigger = Edge, Level = Assert.
     * Command word: 0x00004500
     */
    apic_write(LAPIC_ICR_LOW, (uint32_t)IPI_INIT);

    /* Step 3: Wait ~10 ms for INIT de-assert (Intel SDM §10.6 recommendation). */
    delay_rdtsc_approx_10ms();

    /*
     * Step 4: Send Startup IPI (SIPI).
     * Vector field = 0x07 → AP begins execution at 0x07000 (= 0x7000).
     * Command word: 0x00004607
     *
     * Intel recommends two SIPIs separated by ~200 µs.  We issue one SIPI
     * here and poll the READY flag; if it times out we issue a second.
     */
    apic_write(LAPIC_ICR_HIGH, (uint32_t)ap_id << 24);
    apic_write(LAPIC_ICR_LOW,  (uint32_t)IPI_SIPI_VEC07);

    /* Step 5: Poll ap_ready at 0x7028 with a short timeout (~200 ms). */
    const uint64_t POLL_TICKS = 40000000ULL; /* ~200 ms @ 200 MHz minimum */
    uint64_t t0 = rdtsc();
    while (read64_at(TRAMPOLINE_PHYS_BASE + TRAMP_OFFSET_READY) == 0) {
        if ((rdtsc() - t0) > POLL_TICKS) {
            /* Second SIPI (Intel SDM §10.6 two-SIPI recommendation). */
            apic_write(LAPIC_ICR_HIGH, (uint32_t)ap_id << 24);
            apic_write(LAPIC_ICR_LOW,  (uint32_t)IPI_SIPI_VEC07);
            t0 = rdtsc();
            /* Give the second SIPI another full window. */
            const uint64_t SECOND_WINDOW = 200000000ULL;
            uint64_t t1 = rdtsc();
            while (read64_at(TRAMPOLINE_PHYS_BASE + TRAMP_OFFSET_READY) == 0) {
                if ((rdtsc() - t1) > SECOND_WINDOW) {
                    klog("SMP: AP nao respondeu ao SIPI. Nucleo ignorado.\n");
                    return;
                }
                __asm__ volatile ("pause" ::: "memory");
            }
            break;
        }
        __asm__ volatile ("pause" ::: "memory");
    }

    klog("SMP: AP acordado com sucesso pelo BSP.\n");
}

/* ════════════════════════════════════════════════════════════════════════════
 * Vector D — C entry point for every Application Processor.
 *
 * Called from long_mode_entry in trampoline.asm with:
 *   RDI = ap_id (first argument per SysV AMD64 ABI).
 * ════════════════════════════════════════════════════════════════════════════ */

void ap_kmain(uint64_t ap_id)
{
    (void)ap_id; /* suppress warning if unused below */

    /*
     * Step 1 — Reload the real kernel GDT.
     *
     * The trampoline carried its own minimal temporary GDT.  Now that we
     * are in 64-bit Long Mode we must install the BSP's official GDT so
     * that all selectors (CS=0x08, DS=0x10, TSS, etc.) are coherent.
     */
    __asm__ volatile ("lgdt %0" :: "m"(bsp_gdtr));

    /*
     * After loading the new GDTR the segment descriptor cache for CS still
     * holds the trampoline's selector.  Far-return trick to reload CS=0x08:
     *
     *   push  $0x08         ; target code selector
     *   lea   rax, [rip+8]  ; next instruction address
     *   push  rax
     *   retfq               ; pops RIP then CS
     *
     * We encode this portably with inline asm.
     */
    __asm__ volatile (
        "pushq $0x08\n\t"
        "leaq  1f(%%rip), %%rax\n\t"
        "pushq %%rax\n\t"
        "lretq\n\t"
        "1:\n\t"
        ::: "rax", "memory"
    );

    /* Reload data segment registers to kernel data selector (0x10). */
    __asm__ volatile (
        "movw $0x10, %%ax\n\t"
        "movw %%ax, %%ds\n\t"
        "movw %%ax, %%es\n\t"
        "movw %%ax, %%ss\n\t"
        ::: "rax", "memory"
    );

    /*
     * Step 2 — Enable Local APIC on this secondary core.
     * apic_init_ap() writes the SIVR (offset 0xF0) with software-enable bit.
     */
    apic_init_ap();

    /*
     * Step 3 — Serialized log output.
     *
     * Multiple APs may reach this point concurrently.  We acquire the SMP
     * spinlock to avoid interleaved serial output.
     * klog() MUST receive only a static string literal — no format specifiers.
     */
    spin_lock(&smp_lock);
    klog("SMP: Nucleo secundario inicializado com sucesso.\n");
    /* Atomically record that one more AP has completed boot. */
    __sync_fetch_and_add(&ap_booted_count, 1);
    spin_unlock(&smp_lock);

    /*
     * Step 4 — Safe idle loop.
     *
     * The AP has no scheduler context yet.  Disable interrupts and halt
     * until the future SMP-aware scheduler assigns work to this core.
     */
    for (;;) {
        __asm__ volatile ("cli; hlt" ::: "memory");
    }
}

int smp_ap_booted_count(void)
{
    return ap_booted_count;
}

void smp_tlb_shootdown_handler(void)
{
    uint64_t cr3;
    __asm__ volatile ("mov %%cr3, %0" : "=r"(cr3));
    __asm__ volatile ("mov %0, %%cr3" : : "r"(cr3) : "memory");
    apic_eoi();
}
